name: Dotnet Desktop MsBuild

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'
      - name: add package src
        env:
          dir: ${{ github.workspace }}\src
        run: nuget sources Add -Name "MyLocalSrc" -Source ${{ github.workspace }}\lib
      - name: nuget package restore
        env:
          dir: ${{ github.workspace }}\src
        run: nuget restore
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build DotNET
        run: MSBuild.exe ${{ github.workspace }}\src\ZipMake.csproj

