name: Dotnet Desktop MsBuild

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'
      - name: add package src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          dir: ${{ github.workspace }}\src
        run: nuget sources Add -Name "MyLocalSrc" -Source ${{ github.workspace }}\lib
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build DotNET
        env:
          dir: ${{ github.workspace }}\src
        run: MSBuild.exe ZipMake.sln

